### ISSUE TITLE
安装插件不生效

### ISSUE THREAD

**Issue by MarcusYYDS** [mo-jinran/LiteLoaderQQNT#37]
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/102860926/e04cf898-381d-47e3-9d85-f404fe2dd27d)
![image](https://img1.imgtp.com/2023/07/06/1MxkudX5.png)
![image](https://img1.imgtp.com/2023/07/06/efnSgt6Y.png)
安装后不知道重开了几遍QQnt,重启了几遍电脑,仍然不生效
更新了QQ也不行,求解😍

**Comment by festoney8** [comment]
是否在插件列表里开启了插件?

**Comment by MarcusYYDS** [comment]
插件列表里面没有东西
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/102860926/8f982c97-b47f-45b6-ac54-4ea2a5f65051)

**Comment by festoney8** [comment]
> 左栏没看见插件列表，看起来是插件载入出了问题
> 
> 试一下在命令行运行QQ.exe，看他输出的log，是否载入了插件列表，载入后是否有与插件有关的报错

或者可以尝试逐个移除插件文件夹，检查哪个插件出了问题

**Comment by festoney8** [comment]
截图中anti-recall插件出现了两次 删一个看看

**Comment by MarcusYYDS** [comment]
```sh
$ ./qq.exe
[preload] process type:
[app]module file name: C:\Program Files (x86)\Tencent\QQNT\qq.exe
[preload] hotupdate base version: 9.9.0-14619
[preload] hotupdate current version: 9.9.0-14619
[preload] install app version: 9.9.0-14619

[preload] succeeded. C:\Program Files (x86)\Tencent\QQNT\resources\app\versions\9.9.0-14619\major.node
[preload] succeeded. C:\Program Files (x86)\Tencent\QQNT\resources\app\versions\9.9.0-14619\wrapper.node
[preload] succeeded. C:\Program Files (x86)\Tencent\QQNT\resources\app\app_launcher\launcher.node
BetterQQNT: Initializing...
BetterQQNT: Start loading plugins.
BetterQQNT: Found plugin: LiteLoader 配置界面
BetterQQNT: Plugins loaded with error:  Error: Cannot find module 'chii'
Require stack:
- C:\Users\Administrator\Documents\BetterQQNT\plugins\chii-devtools\src\main.js
- C:\Program Files (x86)\Tencent\QQNT\resources\app\LiteLoader\src\main\loader.js
- C:\Program Files (x86)\Tencent\QQNT\resources\app\LiteLoader\src\main\index.js
- C:\Program Files (x86)\Tencent\QQNT\resources\app\LiteLoader\src\index.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:116708)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at l._load (node:electron/js2c/asar_bundle:2:14200)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Administrator\Documents\BetterQQNT\plugins\chii-devtools\src\main.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\BetterQQNT\\plugins\\chii-devtools\\src\\main.js',
    'C:\\Program Files (x86)\\Tencent\\QQNT\\resources\\app\\LiteLoader\\src\\main\\loader.js',
    'C:\\Program Files (x86)\\Tencent\\QQNT\\resources\\app\\LiteLoader\\src\\main\\index.js',
    'C:\\Program Files (x86)\\Tencent\\QQNT\\resources\\app\\LiteLoader\\src\\index.js',
    undefined
  ]
}
Error: Cannot find module 'chii'
Require stack:
- C:\Users\Administrator\Documents\BetterQQNT\plugins\chii-devtools\src\main.js
- C:\Program Files (x86)\Tencent\QQNT\resources\app\LiteLoader\src\main\loader.js
- C:\Program Files (x86)\Tencent\QQNT\resources\app\LiteLoader\src\main\index.js
- C:\Program Files (x86)\Tencent\QQNT\resources\app\LiteLoader\src\index.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:116708)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at l._load (node:electron/js2c/asar_bundle:2:14200)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Administrator\Documents\BetterQQNT\plugins\chii-devtools\src\main.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Documents\\BetterQQNT\\plugins\\chii-devtools\\src\\main.js',
    'C:\\Program Files (x86)\\Tencent\\QQNT\\resources\\app\\LiteLoader\\src\\main\\loader.js',
    'C:\\Program Files (x86)\\Tencent\\QQNT\\resources\\app\\LiteLoader\\src\\main\\index.js',
    'C:\\Program Files (x86)\\Tencent\\QQNT\\resources\\app\\LiteLoader\\src\\index.js',
    undefined
  ]
}
BetterQQNT: Done! 1 plugins loaded!
BetterQQNT: Starting QQNT...
[preload] register done. launcher.node
[2023/7/7 11:22:27][INFO] C:\Program Files (x86)\Tencent\QQNT\resources\app\versions\config.json 存在

[2023/7/7 11:22:27][INFO] 已经存在 C:\Program Files (x86)\Tencent\QQNT\resources\app\versions\9.9.0-14619 目录，无需执行解压操作

[2023/7/7 11:22:27][INFO] 从版本目录加载主进程代码: C:\Program Files (x86)\Tencent\QQNT\resources\app\versions\9.9.0-14619\application\background.js, {
  "curVersion": "9.9.0-14619",
  "mainProcessFileName": "application\\background.js"
}

[preload] register done. major.node
[preload] register done. wrapper.node
[2023/7/7 11:22:28][INFO]
---------- 华丽的分割线 ----------



[2023-07-07 11:22:29.181] [ERROR] [Main] send on error 9212 /checkAliveServer?da connect ECONNREFUSED 127.0.0.1:9212
[2023-07-07 11:22:29.182] [ERROR] [Main] send on error 9213 /checkAliveServer?da connect ECONNREFUSED 127.0.0.1:9213
[2023-07-07 11:22:29.183] [ERROR] [Main] send on error 9214 /checkAliveServer?da connect ECONNREFUSED 127.0.0.1:9214
[2023-07-07 11:22:29.184] [ERROR] [Main] send on error 9215 /checkAliveServer?da connect ECONNREFUSED 127.0.0.1:9215
[2023-07-07 11:22:29.185] [ERROR] [Main] send on error 9216 /checkAliveServer?da connect ECONNREFUSED 127.0.0.1:9216
[2023-07-07 11:22:29.186] [ERROR] [Main] send on error 9217 /checkAliveServer?da connect ECONNREFUSED 127.0.0.1:9217
[2023-07-07 11:22:29.187] [ERROR] [Main] send on error 9218 /checkAliveServer?da connect ECONNREFUSED 127.0.0.1:9218
[2023-07-07 11:22:29.188] [ERROR] [Main] send on error 9219 /checkAliveServer?da connect ECONNREFUSED 127.0.0.1:9219
[2023-07-07 11:22:29.346] [ERROR] [Main] send on error 9212 /reportPortOpen?data connect ECONNREFUSED 127.0.0.1:9212
[2023-07-07 11:22:29.347] [ERROR] [Main] send on error 9213 /reportPortOpen?data connect ECONNREFUSED 127.0.0.1:9213
[2023-07-07 11:22:29.348] [ERROR] [Main] send on error 9214 /reportPortOpen?data connect ECONNREFUSED 127.0.0.1:9214
[2023-07-07 11:22:29.349] [ERROR] [Main] send on error 9215 /reportPortOpen?data connect ECONNREFUSED 127.0.0.1:9215
[2023-07-07 11:22:29.349] [ERROR] [Main] send on error 9216 /reportPortOpen?data connect ECONNREFUSED 127.0.0.1:9216
[2023-07-07 11:22:29.350] [ERROR] [Main] send on error 9217 /reportPortOpen?data connect ECONNREFUSED 127.0.0.1:9217
[2023-07-07 11:22:29.350] [ERROR] [Main] send on error 9218 /reportPortOpen?data connect ECONNREFUSED 127.0.0.1:9218
[2023-07-07 11:22:29.351] [ERROR] [Main] send on error 9219 /reportPortOpen?data connect ECONNREFUSED 127.0.0.1:9219
[2023-07-07 11:22:45.628] [ERROR] [Main] unhandledRejection invoke nt error: nodeIKernelQQPlayService/closeSimulator. NodeIKernelQQPlayService::closeSimulator : implementation of IKernelQQPlayService is not valid Error: invoke nt error: nodeIKernelQQPlayService/closeSimulator. NodeIKernelQQPlayService::closeSimulator : implementation of IKernelQQPlayService is not valid
    at Proxy.<anonymous> (evalmachine.<anonymous>)
    at evalmachine.<anonymous>
    at new Promise (<anonymous>)
    at d.closeSimulator (evalmachine.<anonymous>)
    at f.closeSimulator (evalmachine.<anonymous>)
    at App.<anonymous> (evalmachine.<anonymous>)
    at App.emit (node:events:513:28)
    at evalmachine.<anonymous>
    at <anonymous>
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-07-07 11:22:45.635] [ERROR] [Main] send on error 9212 /reportPortClose?dat connect ECONNREFUSED 127.0.0.1:9212
[2023-07-07 11:22:45.636] [ERROR] [Main] send on error 9213 /reportPortClose?dat connect ECONNREFUSED 127.0.0.1:9213
[2023-07-07 11:22:45.638] [ERROR] [Main] send on error 9214 /reportPortClose?dat connect ECONNREFUSED 127.0.0.1:9214
[2023-07-07 11:22:45.639] [ERROR] [Main] send on error 9215 /reportPortClose?dat connect ECONNREFUSED 127.0.0.1:9215
[2023-07-07 11:22:45.640] [ERROR] [Main] send on error 9216 /reportPortClose?dat connect ECONNREFUSED 127.0.0.1:9216
[2023-07-07 11:22:45.641] [ERROR] [Main] send on error 9217 /reportPortClose?dat connect ECONNREFUSED 127.0.0.1:9217
[2023-07-07 11:22:45.642] [ERROR] [Main] send on error 9218 /reportPortClose?dat connect ECONNREFUSED 127.0.0.1:9218
[2023-07-07 11:22:45.643] [ERROR] [Main] send on error 9219 /reportPortClose?dat connect ECONNREFUSED 127.0.0.1:9219
```
这是日志
佬帮我看看

**Comment by MarcusYYDS** [comment]
ciil插件有问题
删掉就好了
谢谢佬

**Comment by mo-jinran** [comment]
chii插件需要安装chii依赖
在chii插件目录下执行
```
npm install chii
```
或末尾添加-g参数安装到全局

**Comment by 1003999458** [comment]
![QQ截图20240604104526](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/38431629/910d309b-4d7c-4c55-9a2f-d7a231a86130)
你好，同样的问题，请问这是什么错误
